version: "3.2"
services:
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/var/lib/secrets/root-password.txt"
    volumes:
    - type: bind
      source: ./storage/mysql/init
      target: /docker-entrypoint-initdb.d
    - type: bind
      source: ./storage/mysql/data
      target: /var/lib/mysql
    - type: bind
      source: ./storage/mysql/secrets
      target: /var/lib/secrets
    restart: always

  redis:
    image: "redis:latest"
    restart: always

  backup:
    build: "backup"
    volumes:
    - type: bind
      source: ./storage/backup/archive
      target: /var/lib/backup/archive
    - type: bind
      source: ./storage/backup/wordpress
      target: /var/lib/backup/src/wordpress
    - type: bind
      source: ./storage/backup/redmine
      target: /var/lib/backup/src/redmine
    - type: bind
      source: ./storage/mysql/secrets
      target: /var/lib/secrets/mysql
    depends_on:
    - mysql
    restart: always

  minauth:
    build: "min-auth"
    environment:
      RUST_LOG: info
      REDIS_URI: "redis://redis/0"
      REDIS_LIFETIME: 3600
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME_FILE: "/var/lib/secrets/db-username.txt"
      MYSQL_PASSWORD_FILE: "/var/lib/secrets/db-password.txt"
      MYSQL_DBNAME: minauth
      PASSWORD_SECRET: "secret:"
    volumes:
    - type: bind
      source: ./storage/min-auth/secrets
      target: /var/lib/secrets
    depends_on:
    - mysql
    - redis
    restart: always

  wordpress:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER_FILE: "/var/lib/secrets/db-username.txt"
      WORDPRESS_DB_PASSWORD_FILE: "/var/lib/secrets/db-password.txt"
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - type: bind
      source: ./storage/wordpress/html
      target: /var/www/html
    - type: bind
      source: ./storage/wordpress/secrets
      target: /var/lib/secrets
    depends_on:
    - mysql
    restart: always

  redmine:
    image: "redmine:latest"
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PORT: 3306
      REDMINE_DB_USERNAME_FILE: "/var/lib/secrets/db-username.txt"
      REDMINE_DB_PASSWORD_FILE: "/var/lib/secrets/db-password.txt"
      REDMINE_DB_DATABASE: redmine
    volumes:
    - type: bind
      source: ./storage/redmine/files
      target: /usr/src/redmine/files
    - type: bind
      source: ./storage/redmine/secrets
      target: /var/lib/secrets
    depends_on:
    - mysql
    restart: always

  nginx:
    build: "nginx"
    ports:
    - "80:80"
    - "443:443"
    #- "30022:30022"
    volumes:
    - type: bind
      source: ./storage/nginx/config
      target: /etc/nginx/conf.d
    - type: bind
      source: ./storage/nginx/secrets
      target: /var/lib/secrets
    depends_on:
    - minauth
    - redmine
    - wordpress
    restart: always
