version: "3.2"
services:
  backup:
    build: "backup"
    volumes:
    - type: volume
      source: backup-archives
      target: /var/lib/backup/archive
    - type: volume
      source: wordpress-html
      target: /var/lib/backup/src/wordpress
    - type: volume
      source: redmine-files
      target: /var/lib/backup/src/redmime
    restart: always

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
    - type: volume
      source: mysql-data
      target: /var/lib/mysql
    restart: always

  redis:
    image: "redis:latest"
    restart: always

  minauth:
    image: "min-auth:latest"
    environment:
      RUST_LOG: info
      REDIS_URI: "redis://redis/0"
      REDIS_LIFETIME: 3600
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: minauth
      MYSQL_PASSWORD: minauth
      MYSQL_DBNAME: minauth
      PASSWORD_SECRET: "secret:"
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  wordpress:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - type: volume
      source: wordpress-html
      target: /var/www/html
    depends_on:
      mysql:
        condition: service_started
    restart: always

  redmine:
    image: "redmine:latest"
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PORT: 3306
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    volumes:
    - type: volume
      source: redmine-files
      target: /usr/src/redmine/files
    depends_on:
      mysql:
        condition: service_started
    restart: always

  nginx:
    build: nginx
    ports:
    - "80:80"
    - "443:443"
    #- "30022:30022"
    depends_on:
      minauth:
        condition: service_started
      redmine:
        condition: service_started
      wordpress:
        condition: service_started
    restart: always

volumes:
  backup-archives:
    external: true
  mysql-data:
    external: true
  wordpress-html:
    external: true
  redmine-files:
    external: true
