version: "3.2"
services:
  backup:
    image: "backup:latest"
    volumes:
    - type: volume
      source: backup-archives
      target: /var/lib/backup/archive
    - type: volume
      source: wordpress-html
      target: /var/lib/backup/src/wordpress
    - type: volume
      source: redmine-files
      target: /var/lib/backup/src/redmine
    secrets:
    - minauth-db-username
    - minauth-db-password
    - wordpress-db-username
    - wordpress-db-password
    - redmine-db-username
    - redmine-db-password

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql-root-password"
    secrets:
    - mysql-root-password
    volumes:
    - type: volume
      source: mysql-data
      target: /var/lib/mysql

  redis:
    image: "redis:latest"
    restart: always

  minauth:
    image: "min-auth:latest"
    environment:
      RUST_LOG: info
      REDIS_URI: "redis://redis/0"
      REDIS_LIFETIME: 3600
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME_FILE: "/run/secrets/minauth-db-username"
      MYSQL_PASSWORD_FILE: "/run/secrets/minauth-db-password"
      MYSQL_DBNAME: minauth
      PASSWORD_SECRET: "secret:"
    secrets:
    - minauth-db-username
    - minauth-db-password
    depends_on:
    - mysql
    - redis

  wordpress:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER_FILE: "/run/secrets/wordpress-db-username"
      WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wordpress-db-password"
      WORDPRESS_DB_NAME: wordpress
    secrets:
    - wordpress-db-username
    - wordpress-db-password
    volumes:
    - type: volume
      source: wordpress-html
      target: /var/www/html
    depends_on:
    - mysql

  redmine:
    image: "redmine:latest"
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PORT: 3306
      REDMINE_DB_USERNAME_FILE: "/run/secrets/redmine-db-username"
      REDMINE_DB_PASSWORD_FILE: "/run/secrets/redmine-db-password"
      REDMINE_DB_DATABASE: redmine
    secrets:
    - redmine-db-username
    - redmine-db-password
    volumes:
    - type: volume
      source: redmine-files
      target: /usr/src/redmine/files
    depends_on:
    - mysql

  nginx:
    image: "nginx:latest"
    ports:
    - "80:80"
    - "443:443"
    #- "30022:30022"
    depends_on:
    - minauth
    - redmine
    - wordpress

secrets:
  mysql-root-password:
    external: true
  minauth-db-username:
    external: true
  minauth-db-password:
    external: true
  wordpress-db-username:
    external: true
  wordpress-db-password:
    external: true
  redmine-db-username:
    external: true
  redmine-db-password:
    external: true

volumes:
  backup-archives:
    external: true
  mysql-data:
    external: true
  wordpress-html:
    external: true
  redmine-files:
    external: true
