#!/bin/sh

TS=$(date +%Y%m%d%H%M%S%N)

BKHOME="/var/lib/backup"
SRCDIR="${BKHOME}/src"
DSTDIR="${BKHOME}/dst"
ARCHDIR="${BKHOME}/archives"

DBPASS="$(cat /var/lib/secrets/mysql/root-password.txt)"

# Delete the last backup.
if ! rm -rf "${DSTDIR}" ; then
	echo "Failed to delete the previous backup." 1>&2
	exit 1
fi

# Make a directory to create an archive.
if ! mkdir -p "${DSTDIR}" ; then
	echo "Failed to create the backup directory." 1>&2
	exit 2
fi

# Copy files to the directory that will be archived.
{
	echo wordpress
	echo redmine
} | while read SVC ; do
	if ! rsync -a "${SRCDIR}/${SVC}/" "${DSTDIR}/${SVC}" ; then
		echo "Failed to sync \"${SRCDIR}/${SVC}.\"" 1>&2
		exit 3
	fi
done

# Dump the databases.
{
	echo minauth
	echo wordpress
	echo redmine
} | while read DBNAME ; do
	if ! mysqldump -h"mysql" -u"root" -p"${DBPASS}" --hex-blob "${DBNAME}" > "${DSTDIR}/${DBNAME}.sql" ; then
		echo "Failed to dump the ${DBNAME} database." 1>&2
		exit 4
	fi
done

# Create an archive file.
if ! tar -czf "${ARCHDIR}/${TS}.tar.gz" -C "${DSTDIR}" . ; then
	echo "Failed to archive the target files." 1>&2
	exit 5
fi

# Delete old archives.
if ! find "${DSTDIR}" -type f -name "*.tar.gz" -mtime "+30" -exec rm -f "{}" \; ; then
	echo "Failed to delete old archives." 1>&2
	exit 6
fi
