#!/bin/sh

TS=$(date +%Y%m%d%H%M%S%N)

BKHOME="/var/lib/backup"
SRCDIR="${BKHOME}/src"
DSTDIR="${BKHOME}/dst"
ARCHDIR="${BKHOME}/archives"

if ! rm -rf "${DSTDIR}" ; then
    echo "Failed to delete the previous backup." 1>&2
    exit 1
fi

if ! mkdir -p "${DSTDIR}" ; then
    echo "Failed to create the backup directory." 1>&2
    exit 2
fi

if ! rm -rf "${ARCHDIR}/*.tar.gz" ; then
    echo "Failed to delete the previous archive." 1>&2
    exit 1
fi

{
    echo redmine
    echo wordpress
} | while read SVC ; do
    if ! rsync -a "${SRCDIR}/${SVC}" "${DSTDIR}/${SVC}" ; then
        echo "Failed to sync \"${SRCDIR}/${SVC}.\"" 1>&2
        exit 3
    fi
done

if ! tar -czf "${ARCHDIR}/${TS}.tar.gz" -C "${DSTDIR}" . ; then
    echo "Failed to archive the target files."
    exit 4
fi
